In [106]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np
#kutuphaneler yuklendi

@author= MUSTAFA YALINIZ

In [107]:
#veri csv dosyasi pandas ile okundu
df=pd.read_csv('eksikveriler.csv')
df

ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [108]:
#NaN degerleri olan sutunlar alindi ortalamasi hesaplandi 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(df[['yas','boy','kilo']].values)
yas=imputer.transform(df[['yas','boy','kilo']].values)
yas # 28.45 olarak Nan degerlerini doldurdu

array([[ 10.  , 130.  ,  30.  ],
       [ 11.  , 125.  ,  36.  ],
       [ 10.  , 135.  ,  34.  ],
       [  9.  , 133.  ,  30.  ],
       [ 12.  , 129.  ,  38.  ],
       [ 30.  , 180.  ,  90.  ],
       [ 25.  , 190.  ,  80.  ],
       [ 35.  , 175.  ,  90.  ],
       [ 22.  , 177.  ,  60.  ],
       [ 33.  , 185.  , 105.  ],
       [ 27.  , 165.  ,  55.  ],
       [ 44.  , 155.  ,  50.  ],
       [ 28.45, 160.  ,  58.  ],
       [ 41.  , 162.  ,  59.  ],
       [ 55.  , 167.  ,  62.  ],
       [ 47.  , 174.  ,  70.  ],
       [ 28.45, 193.  ,  90.  ],
       [ 27.  , 187.  ,  80.  ],
       [ 28.  , 183.  ,  88.  ],
       [ 29.  , 159.  ,  40.  ],
       [ 32.  , 164.  ,  66.  ],
       [ 42.  , 166.  ,  56.  ]])

In [109]:
#encoder kutuphaneleri yuklendi
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

In [110]:
df=pd.read_csv('veriler.csv')
ulke=df[['ulke']].values
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [111]:
#labelencoder ile sayisal veriye donusturuyorum
le=LabelEncoder()
data=le.fit_transform(ulke[:,0])
data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0])

In [112]:
#tek boyutlu (1,22) matrisi (22,1) ceviriyorum
data=data.reshape(-1,1)
data

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [113]:
#onehotencoder kategorik veriyi sayisal veriye donusturuyorum
ohe=OneHotEncoder(categories='auto')
data=ohe.fit_transform(data).toarray()
ulke=data
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [114]:
#veriden sutun alma 
cinsiyet=df[['cinsiyet']].values
cinsiyet

array([['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [115]:
#ordinal veriyi label encode ediyoruz
cinsiyet=le.fit_transform(cinsiyet[:,0])
cinsiyet=cinsiyet.reshape(-1,1)
cinsiyet

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [116]:
#Dataframe olusturma veriye baslik ekleme 
sonuc=pd.DataFrame(data=yas,columns=['yas','boy','kilo'])
sonuc1=pd.DataFrame(data=cinsiyet,columns=['cinsiyet'])
sonuc2=pd.DataFrame(data=ulke,columns=['fr','tr','us']) 
sonuc2

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [117]:
#Dataframeleri birlestirme 
data=pd.concat([sonuc,sonuc2],axis=1)#axis satir sutun belli ediyor
data

yas    boy   kilo   fr   tr   us
0   10.00  130.0   30.0  0.0  1.0  0.0
1   11.00  125.0   36.0  0.0  1.0  0.0
2   10.00  135.0   34.0  0.0  1.0  0.0
3    9.00  133.0   30.0  0.0  1.0  0.0
4   12.00  129.0   38.0  0.0  1.0  0.0
5   30.00  180.0   90.0  0.0  1.0  0.0
6   25.00  190.0   80.0  0.0  1.0  0.0
7   35.00  175.0   90.0  0.0  1.0  0.0
8   22.00  177.0   60.0  0.0  1.0  0.0
9   33.00  185.0  105.0  0.0  0.0  1.0
10  27.00  165.0   55.0  0.0  0.0  1.0
11  44.00  155.0   50.0  0.0  0.0  1.0
12  28.45  160.0   58.0  0.0  0.0  1.0
13  41.00  162.0   59.0  0.0  0.0  1.0
14  55.00  167.0   62.0  0.0  0.0  1.0
15  47.00  174.0   70.0  1.0  0.0  0.0
16  28.45  193.0   90.0  1.0  0.0  0.0
17  27.00  187.0   80.0  1.0  0.0  0.0
18  28.00  183.0   88.0  1.0  0.0  0.0
19  29.00  159.0   40.0  1.0  0.0  0.0
20  32.00  164.0   66.0  1.0  0.0  0.0
21  42.00  166.0   56.0  1.0  0.0  0.0

In [118]:
#veriyi train ve test icin kutuphaneler
from sklearn.model_selection import train_test_split

In [119]:
#x bagimsiz degisken y bagimli desgisken yuzde 33  olarak ayirdik butun veriyi
x_train,x_test,y_train,y_test=train_test_split(data,sonuc1,test_size=0.33,random_state=42) 

In [120]:
#data olceklendirme kutuphanesi 
from sklearn.preprocessing import StandardScaler

In [121]:
#datayi olceklendiriyoruz 
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)
X_train

array([[-1.59044249, -1.60676649, -1.4892569 , -0.74535599,  1.34164079,
        -0.63245553],
       [-1.33635887, -1.80026956, -1.14605366, -0.74535599,  1.34164079,
        -0.63245553],
       [-0.06594075,  1.00552484,  0.65576333,  1.34164079, -0.74535599,
        -0.63245553],
       [ 0.05686633, -0.30062083, -0.28804557, -0.74535599, -0.74535599,
         1.58113883],
       [ 0.01875379,  0.81202178,  0.99896656,  1.34164079, -0.74535599,
        -0.63245553],
       [ 0.05686633,  1.29577943,  1.08476737,  1.34164079, -0.74535599,
        -0.63245553],
       [-1.50574795, -1.51001496, -1.31765528, -0.74535599,  1.34164079,
        -0.63245553],
       [ 0.4422265 ,  0.90877331,  1.72827344, -0.74535599, -0.74535599,
         1.58113883],
       [ 1.20447737, -0.01036624, -0.37384638,  1.34164079, -0.74535599,
        -0.63245553],
       [ 0.61161558,  0.42501565,  1.08476737, -0.74535599,  1.34164079,
        -0.63245553],
       [-0.06594075, -0.058742  , -0.41674679, -0.