In [326]:
import  numpy as np

@Author= MUSTAFA YALINIZ

In [327]:
#rastgele sayi üremte 
data =np.random.rand(3,3)
data

array([[0.02948437, 0.1198556 , 0.31590565],
       [0.42557737, 0.85989222, 0.14166177],
       [0.81957958, 0.3931829 , 0.05761   ]])

In [328]:
#matris boyutunu ogrenme
data.shape

(3, 3)

In [329]:
#veri tipini ogrenme
data.dtype

dtype('float64')

In [330]:
#dizi olusturma 
veri=(1,2,3,4)
df=np.array(veri)
df

array([1, 2, 3, 4])

In [331]:
#dizi olusturma 2
veri1=[[1,2,3],[4,5,6]]
data=np.array(veri1)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [332]:
#dizi olusturma 3
data=np.array(5,dtype=np.float64)
data

array(5.)

In [333]:
#sifirli dizi olusturma 
data=np.zeros((3,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [334]:
#sifirli dizi olusturma 2
data=np.zeros(5)
data

array([0., 0., 0., 0., 0.])

In [335]:
#elemanlari '1' li dizi olusturma 
data=np.ones((3,3))
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [336]:
#elemanlari '1' li dizi olusturma 2
data=np.ones(5,dtype=np.int32) #tam sayili
data

array([1, 1, 1, 1, 1])

In [337]:
#bos dizi olusturma 
data=np.empty((2,2,2))
data

array([[[0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000]],

       [[0.0000e+000, 1.2233e-320],
        [0.0000e+000, 0.0000e+000]]])

In [338]:
#sirali dizi olusturma 
data=np.arange(10,dtype=np.float64) #veri tipi float
data

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [339]:
#veri tipini degistirme
veri =np.array([1.3,2.3,3.3,4.5,5.5,6.5])
data=veri.astype(int)
data

array([1, 2, 3, 4, 5, 6])

In [340]:
#veri tipini degistirme 2
numeric_string=np.array([1.212,2.56,3.654,4.54,5.86,6.12,7.86,8.876,9.11],dtype=np.string_) #veri tipi string
data=numeric_string.astype(float)
data

array([1.212, 2.56 , 3.654, 4.54 , 5.86 , 6.12 , 7.86 , 8.876, 9.11 ])

In [341]:
#matris boyutlandirma 
data=np.arange(9)
data=data.reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [342]:
#kokunu alma 
arr=np.arange(5)
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [343]:
#e^x alma 
np.exp(arr) #exp = e^x

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [344]:
#dosya kaydetme 
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.save('data.npy',data)

In [345]:
#dosya okuma 
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [346]:
#matris toplami 
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Toplama
C = A + B

C

array([[ 8, 10, 12],
       [14, 16, 18]])

In [347]:
#matris carpimi 
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6.23],[-1.27],[8.9]])

x.dot(y) # np.dot(x,y) bu da calisir 

array([[30.39],
       [71.97]])

In [348]:
#iki matrisin karsilikli gelen elemanlari carpimi 
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])


C = A * B
C

array([[ 7, 16, 27],
       [40, 55, 72]])

In [349]:
#matrisin transpozu 
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A_T = A.T
A_T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [350]:
#matrisin determinanti
A = np.array([[1, 2],
              [3, 4]])

det = np.linalg.det(A) #det fonksiyonu determinantini aliyor
det

-2.0000000000000004

In [351]:
#matrisin tersi 
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A) # inv fonksiyonu tersini aliyor 
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])