In [1]:
import  numpy as np

@Author= MUSTAFA YALINIZ

In [2]:
#rastgele sayi üremte 
data =np.random.rand(3,3)
data

array([[0.77786968, 0.3248955 , 0.86582183],
       [0.09063506, 0.50096238, 0.34822633],
       [0.50315097, 0.15584996, 0.27440795]])

In [3]:
#matris boyutunu ogrenme
data.shape

(3, 3)

In [4]:
#veri tipini ogrenme
data.dtype

dtype('float64')

In [5]:
#dizi olusturma 
veri=(1,2,3,4)
df=np.array(veri)
df

array([1, 2, 3, 4])

In [6]:
#dizi olusturma 2
veri1=[[1,2,3],[4,5,6]]
data=np.array(veri1)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#dizi olusturma 3
data=np.array(5,dtype=np.float64)
data

array(5.)

In [8]:
#sifirli dizi olusturma 
data=np.zeros((3,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#sifirli dizi olusturma 2
data=np.zeros(5)
data

array([0., 0., 0., 0., 0.])

In [10]:
#elemanlari '1' li dizi olusturma 
data=np.ones((3,3))
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#elemanlari '1' li dizi olusturma 2
data=np.ones(5,dtype=np.int32) #tam sayili
data

array([1, 1, 1, 1, 1])

In [12]:
#bos dizi olusturma 
data=np.empty((2,2,2))
data

array([[[4.67296746e-307, 1.69121096e-306],
        [7.56607956e-307, 1.89146896e-307]],

       [[7.56571288e-307, 3.11525958e-307],
        [1.24610723e-306, 1.29061142e-306]]])

In [13]:
#sirali dizi olusturma 
data=np.arange(10,dtype=np.float64) #veri tipi float
data

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
#veri tipini degistirme
veri =np.array([1.3,2.3,3.3,4.5,5.5,6.5])
data=veri.astype(int)
data

array([1, 2, 3, 4, 5, 6])

In [15]:
#veri tipini degistirme 2
numeric_string=np.array([1.212,2.56,3.654,4.54,5.86,6.12,7.86,8.876,9.11],dtype=np.string_) #veri tipi string
data=numeric_string.astype(float)
data

array([1.212, 2.56 , 3.654, 4.54 , 5.86 , 6.12 , 7.86 , 8.876, 9.11 ])

In [16]:
#matris boyutlandirma 
data=np.arange(9)
data=data.reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# Dizi birlestirme
dizi1 = np.array([1, 2, 3])
dizi2 = np.array([4, 5, 6])

birlesmis_dizi = np.vstack((dizi1, dizi2))
birlesmis_dizi

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#kokunu alma 
arr=np.arange(5)
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [19]:
#e^x alma 
np.exp(arr) #exp = e^x

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [20]:
#dosya kaydetme 
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.save('data.npy',data)

In [21]:
#dosya okuma 
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
#matris toplami 
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Toplama
C = A + B

C

array([[ 8, 10, 12],
       [14, 16, 18]])

In [23]:
#matris carpimi 
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6.23],[-1.27],[8.9]])

x.dot(y) # np.dot(x,y) bu da calisir 

array([[30.39],
       [71.97]])

In [24]:
#iki matrisin karsilikli gelen elemanlari carpimi 
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])


C = A * B
C

array([[ 7, 16, 27],
       [40, 55, 72]])

In [25]:
#matrisin transpozu 
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A_T = A.T
A_T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
#matrisin determinanti
A = np.array([[1, 2],
              [3, 4]])

det = np.linalg.det(A) #det fonksiyonu determinantini aliyor
det

-2.0000000000000004

In [27]:
#matrisin tersi 
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A) # inv fonksiyonu tersini aliyor 
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
#matristen sutun cikarma 
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
data=np.delete(data,1,axis=1) #2.sutun cikardim
data

array([[1, 3],
       [4, 6],
       [7, 9]])

In [29]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
data=np.delete(data,1,axis=0) #2.satiri cikardim
data

array([[1, 2, 3],
       [7, 8, 9]])