In [301]:
import  numpy as np

@Author= MUSTAFA YALINIZ

In [302]:
#rastgele sayi üremte 
data =np.random.rand(3,3)
data

array([[0.89699492, 0.61507787, 0.15718468],
       [0.05083816, 0.31747002, 0.68919254],
       [0.43457147, 0.4870846 , 0.48274604]])

In [303]:
#matris boyutunu ogrenme
data.shape

(3, 3)

In [304]:
#veri tipini ogrenme
data.dtype

dtype('float64')

In [305]:
#dizi olusturma 
veri=(1,2,3,4)
df=np.array(veri)
df

array([1, 2, 3, 4])

In [306]:
#dizi olusturma 2
veri1=[[1,2,3],[4,5,6]]
data=np.array(veri1)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [307]:
#dizi olusturma 3
data=np.array(5,dtype=np.float64)
data

array(5.)

In [308]:
#sifirli dizi olusturma 
data=np.zeros((3,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [309]:
#sifirli dizi olusturma 2
data=np.zeros(5)
data

array([0., 0., 0., 0., 0.])

In [310]:
#elemanlari '1' li dizi olusturma 
data=np.ones((3,3))
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [311]:
#elemanlari '1' li dizi olusturma 2
data=np.ones(5,dtype=np.int32) #tam sayili
data

array([1, 1, 1, 1, 1])

In [312]:
#bos dizi olusturma 
data=np.empty((2,2,2))
data

array([[[0.0000e+000, 0.0000e+000],
        [0.0000e+000, 0.0000e+000]],

       [[0.0000e+000, 1.2233e-320],
        [0.0000e+000, 0.0000e+000]]])

In [313]:
#sirali dizi olusturma 
data=np.arange(10,dtype=np.float64) #veri tipi float
data

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [314]:
#veri tipini degistirme
veri =np.array([1.3,2.3,3.3,4.5,5.5,6.5])
data=veri.astype(int)
data

array([1, 2, 3, 4, 5, 6])

In [315]:
#veri tipini degistirme 2
numeric_string=np.array([1.212,2.56,3.654,4.54,5.86,6.12,7.86,8.876,9.11],dtype=np.string_) #veri tipi string
data=numeric_string.astype(float)
data

array([1.212, 2.56 , 3.654, 4.54 , 5.86 , 6.12 , 7.86 , 8.876, 9.11 ])

In [316]:
#matris boyutlandirma 
data=np.arange(9)
data=data.reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [317]:
#kokunu alma 
arr=np.arange(5)
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [318]:
#e^x alma 
np.exp(arr) #exp = e^x

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [319]:
#dosya kaydetme 
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.save('data.npy',data)

In [320]:
#dosya okuma 
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [321]:
#matris carpimi 
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6.23],[-1.27],[8.9]])

x.dot(y) # np.dot(x,y) bu da calisir 

array([[30.39],
       [71.97]])